apiVersion: skaffold/v1beta16
kind: Config
build:
  artifacts:
  - image: k8s-skaffold/radar-image-pyspark
deploy:
  kubectl:
    manifests:
      - k8s-*
portForward:
  - resourceType: pod
    resourceName: radar-docker-pyspark
    namespace: default
    port: 8888
    localPort: 8891
  - resourceType: pod
    resourceName: radar-docker-pyspark
    namespace: default
    port: 22
    localPort: 22